# 🔗 Links:
# FIXME: change to yarn
# Source file: https://github.com/obytes/react-native-template-obytes/blob/master/.github/actions/setup-node-pnpm-install/action.yml
# Composite actions docs: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

# ✍️ Description:
# This is a composite action, which means it can be used in other actions.
# It is used in almost all workflows to set up the environment and install dependencies.
# Updating  the package manager or Node version here will be reflected in all workflows.

# 👀 Example usage:
#       - name : 📦 Setup Node + YARN + install deps
#         uses: ./.github/actions/setup-node-yarn-install

name: 'Setup  Node + YARN + Install Dependencies'
description: 'Setup  Node + YARN + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version

    - run: corepack enable
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
