type Config = {
  AUTH_BASE_URL: string;

  CONFIDENTIAL_ASSET_MODULE_ADDR: string;
  DEFAULT_TOKEN_ADRESSES: string[];

  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;

  APPLE_CLIENT_ID: string;
  APPLE_CLIENT_SECRET: string;

  FORCE_MAINTENANCE_PAGE: boolean;
};

export const APT_FA_ADDR =
  '0x000000000000000000000000000000000000000000000000000000000000000a';
export const USDC_MOCKED_TOKEN_ADDR =
  '0xeb0d77ea72ab6838c870fc98ed9ea3e12e72fa964021be983b398824ebdd126e';

export const config: Config = {
  AUTH_BASE_URL: process.env.AUTH_BASE_URL!,
  CONFIDENTIAL_ASSET_MODULE_ADDR:
    process.env.NEXT_PUBLIC_CONFIDENTIAL_ASSET_MODULE_ADDR!,
  DEFAULT_TOKEN_ADRESSES: [
    APT_FA_ADDR,
    // USDC_MOCKED_TOKEN_ADDR,
  ],

  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,

  APPLE_CLIENT_ID: process.env.NEXT_PUBLIC_APPLE_CLIENT_ID!,
  APPLE_CLIENT_SECRET: process.env.APPLE_CLIENT_SECRET!,

  FORCE_MAINTENANCE_PAGE: process.env.FORCE_MAINTENANCE_PAGE === 'true',
};
