name: TS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check (types, lint, format)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-yarn-install

      - run: pnpm type-check
      - run: pnpm lint:check
      - run: pnpm format:check
